// APA 7th edition reference list for reviews/discount-rates.md.
// *text* marks italics. A trailing † means some details (authors, volume/pages, title or date)
// were not confirmed against the source and should be checked before formal use.
module.exports = [
  "Agency for Care Effectiveness. (n.d.). *Process and methods guides*. Ministry of Health, Singapore. https://www.ace-hta.gov.sg/resources/process-methods/ †",
  "Allcott, H., & Wozny, N. (2014). Gasoline prices, fuel economy, and the energy paradox. *Review of Economics and Statistics, 96*(5), 779–795. https://doi.org/10.1162/REST_a_00419",
  "Andersen, S., Harrison, G. W., Lau, M. I., & Rutström, E. E. (2008). Eliciting risk and time preferences. *Econometrica, 76*(3), 583–618. https://doi.org/10.1111/j.1468-0262.2008.00848.x",
  "Andreoni, J., & Sprenger, C. (2012). Estimating time preferences from convex budgets. *American Economic Review, 102*(7), 3333–3356. https://doi.org/10.1257/aer.102.7.3333",
  "Arrow, K. J., & Lind, R. C. (1970). Uncertainty and the evaluation of public investment decisions. *American Economic Review, 60*(3), 364–378.",
  "Arrow, K., Cropper, M., Gollier, C., Groom, B., Heal, G., Newell, R., Nordhaus, W., Pindyck, R., Pizer, W., Portney, P., Sterner, T., Tol, R. S. J., & Weitzman, M. (2013). Determining benefits and costs for future generations. *Science, 341*(6144), 349–350. https://doi.org/10.1126/science.1235665",
  "Asian Development Bank. (2017). *Guidelines for the economic analysis of projects*. https://www.adb.org/documents/guidelines-economic-analysis-projects",
  "Association of State Floodplain Managers. (2025). *FEMA rolls back BCA rates for mitigation projects*. https://www.floods.org/news-views/fema-news/fema-rolls-back-bca-rates-for-mitigation-projects/",
  "Augenblick, N., Niederle, M., & Sprenger, C. (2015). Working over time: Dynamic inconsistency in real effort tasks. *Quarterly Journal of Economics, 130*(3), 1067–1115. https://doi.org/10.1093/qje/qjv020",
  "Bank of Finland. (2024). Recent insights into r-star: An analysis using a modified Holston-Laubach-Williams model. *Bank of Finland Bulletin*. https://www.bofbulletin.fi/en/2024/articles/recent-insights-into-r-star-an-analysis-using-a-modified-holston-laubach-williams-model/ †",
  "Barrage, L., & Nordhaus, W. (2024). Policies, projections, and the social cost of carbon: Results from the DICE-2023 model. *Proceedings of the National Academy of Sciences, 121*(13), Article e2312030121. https://doi.org/10.1073/pnas.2312030121",
  "Blanchard, O. (2019). Public debt and low interest rates. *American Economic Review, 109*(4), 1197–1229. https://doi.org/10.1257/aer.109.4.1197",
  "Burgess, D. F., & Zerbe, R. O. (2011). Appropriate discounting for benefit-cost analysis. *Journal of Benefit-Cost Analysis, 2*(2). †",
  "Busse, M. R., Knittel, C. R., & Zettelmeyer, F. (2013). Are consumers myopic? Evidence from new and used car purchases. *American Economic Review, 103*(1), 220–256. https://doi.org/10.1257/aer.103.1.220",
  "CADTH. (2017). *Guidelines for the economic evaluation of health technologies: Canada* (4th ed.). https://www.cda-amc.ca/guidelines-economic-evaluation-health-technologies-canada-4th-edition",
  "CapitaLand Integrated Commercial Trust. (2024). *Annual report 2024*. https://investor.cict.com.sg/misc/ar2024/139/",
  "CapitaLand Integrated Commercial Trust. (2025). *Annual report 2025*. https://investor.cict.com.sg/misc/ar2025/",
  "CBRE. (2026). *U.S. cap rate survey H2 2025*. https://www.cbre.com/insights/reports/us-cap-rate-survey-h2-2025",
  "Center for Outcomes Research and Economic Evaluation for Health. (n.d.). *Guideline for preparing cost-effectiveness evaluation*. National Institute of Public Health, Japan. https://c2h.niph.go.jp/tools/guideline/guideline_en.pdf †",
  "Centre for Liveable Cities. (n.d.). *Bala's Table* [Working paper]. https://isomer-user-content.by.gov.sg/50/ade6cd16-890b-4a1b-9d1d-d0e189daba03/balas-table.pdf †",
  "Chambers, D., Spaenjers, C., & Steiner, E. (2021). The rate of return on real estate: Long-run micro-level evidence. *Review of Financial Studies, 34*(8), 3572–3607. †",
  "Cheung, S. L., Tymula, A., & Wang, X. (2021). *Quasi-hyperbolic present bias: A meta-analysis* (IZA Discussion Paper No. 14625). IZA Institute of Labor Economics. https://docs.iza.org/dp14625.pdf (updated version 2025, SSRN: https://papers.ssrn.com/abstract=5222564) †",
  "Cochrane, J. H. (2011). Presidential address: Discount rates. *Journal of Finance, 66*(4), 1047–1108. https://doi.org/10.1111/j.1540-6261.2011.01671.x",
  "Cohen, J., Ericson, K. M., Laibson, D., & White, J. M. (2020). Measuring time preferences. *Journal of Economic Literature, 58*(2), 299–347. https://doi.org/10.1257/jel.20191074",
  "Congressional Research Service. (n.d.). *The social cost of greenhouse gases* (CRS In Focus IF12916). https://www.congress.gov/crs-product/IF12916 †",
  "Cropper, M. L., Freeman, M. C., Groom, B., & Pizer, W. A. (2014). Declining discount rates. *American Economic Review, 104*(5), 538–543. https://doi.org/10.1257/aer.104.5.538",
  "Damodaran, A. (2026e, January). *Musings on markets* [Blog posts on the implied equity risk premium]. https://aswathdamodaran.blogspot.com/2026/01/ †",
  "Damodaran, A. (2026d). *Data update 5 for 2026: Risk and hurdle rates* [Blog post]. https://aswathdamodaran.substack.com/p/data-update-5-for-2026-risk-and-hurdle",
  "Damodaran, A. (2026a). *Country risk: Determinants, measures and implications* [Blog post]. https://aswathdamodaran.substack.com/p/country-risk-determinants-measures †",
  "Damodaran, A. (2026b, July). *Country risk: Drivers, measures and implications* [Blog post]. https://aswathdamodaran.blogspot.com/2026/07/country-risk-drivers-measures-and.html †",
  "Damodaran, A. (2026c). *Cost of capital by sector (US)* [Data set]. NYU Stern School of Business. https://pages.stern.nyu.edu/~adamodar/New_Home_Page/datafile/wacc.html",
  "Del Negro, M., Giannone, D., Giannoni, M. P., & Tambalotti, A. (2019). Global trends in interest rates. *Journal of International Economics, 118*, 248–262. https://www.nber.org/papers/w25039",
  "Dietz, S., Gollier, C., & Kessler, L. (2018). The climate beta. *Journal of Environmental Economics and Management, 87*, 258–274.",
  "Dimson, E., Marsh, P., & Staunton, M. (2025). *UBS global investment returns yearbook 2025*. UBS. https://www.ubs.com/global/en/media/display-page-ndp/en-20250304-global-investment-returns-yearbook-2025.html",
  "Drupp, M. A., Freeman, M. C., Groom, B., & Nesje, F. (2018). Discounting disentangled. *American Economic Journal: Economic Policy, 10*(4), 109–134. https://doi.org/10.1257/pol.20160240",
  "Eichholtz, P., Korevaar, M., Lindenthal, T., & Tallec, R. (2021). The total return and risk to residential real estate. *Review of Financial Studies, 34*(8), 3608–3646. †",
  "European Central Bank. (2026). *Key ECB interest rates*. https://www.ecb.europa.eu/stats/policy_and_exchange_rates/key_ecb_interest_rates/html/index.en.html",
  "Falk, A., Becker, A., Dohmen, T., Enke, B., Huffman, D., & Sunde, U. (2018). Global evidence on economic preferences. *Quarterly Journal of Economics, 133*(4), 1645–1692. https://doi.org/10.1093/qje/qjy013",
  "Federal Ministry for Digital and Transport. (n.d.). *Bundesverkehrswegeplan 2030* [Federal transport infrastructure plan 2030]. https://www.bmv.de/DE/Themen/Mobilitaet/Infrastrukturplanung-Investitionen/Bundesverkehrswegeplan-2030/bundesverkehrswegeplan-2030.html",
  "Federal Reserve Board. (2026, September 16). *Implementation note issued September 16, 2026* [Press release]. https://www.federalreserve.gov/newsevents/pressreleases/monetary20260916a1.htm",
  "Fernandez, P., et al. (2025). *Survey: Market risk premium and risk-free rate used for 54 countries in 2025* [Summarised by BVResources]. https://www.bvresources.com/articles/bvwire/global-fernandezs-survey-of-2025-risk-premiums-and-risk-free-rates †",
  "Fesselmeyer, E., Liu, H., & Salvo, A. (2016). *How do households discount over centuries? Evidence from Singapore's private housing market* (IZA Discussion Paper No. 9862). https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2761339 (reported as published in *Journal of Applied Econometrics*, 2022: https://onlinelibrary.wiley.com/doi/10.1002/jae.2867) †",
  "France Stratégie. (2021). *Révision du taux d'actualisation* [Revision of the discount rate]. https://www.strategie-plan.gouv.fr/files/files/Edito%20Riche/ESE/fs-guide-evaluation-i-taux_dactualisation-23novembre-final.pdf †",
  "Frederick, S., Loewenstein, G., & O'Donoghue, T. (2002). Time discounting and time preference: A critical review. *Journal of Economic Literature, 40*(2), 351–401. https://doi.org/10.1257/002205102320161311",
  "Freeman, M. C., & Groom, B. (2015). Positively gamma discounting: Combining the opinions of experts on the social discount rate. *Economic Journal, 125*(585), 1015–1024.",
  "Giglio, S., Maggiori, M., & Stroebel, J. (2015). Very long-run discount rates. *Quarterly Journal of Economics, 130*(1), 1–53. https://doi.org/10.1093/qje/qju036",
  "Giglio, S., Maggiori, M., Rao, K., Stroebel, J., & Weber, A. (2021). Climate change and long-run discount rates: Evidence from real estate. *Review of Financial Studies, 34*(8), 3527–3571. https://doi.org/10.1093/rfs/hhab032",
  "Global Property Guide. (2026). *Singapore rental yields*. https://www.globalpropertyguide.com/asia/singapore/rental-yields",
  "Gollier, C. (2012). *Pricing the planet's future: The economics of discounting in an uncertain world*. Princeton University Press.",
  "Gollier, C., & Weitzman, M. L. (2010). How should the distant future be discounted when discount rates are uncertain? *Economics Letters, 107*(3), 350–353.",
  "Gormsen, N. J., & Huber, K. (2025). Corporate discount rates. *American Economic Review, 115*(6), 2001–2049. https://doi.org/10.1257/aer.20231246",
  "Gourinchas, P.-O., & Parker, J. A. (2002). Consumption over the life cycle. *Econometrica, 70*(1), 47–89. https://doi.org/10.1111/1468-0262.00269",
  "Graham, J. R., & Harvey, C. R. (2017). *Duke CFO global business outlook* [Survey results reported in \"CFOs still spurning value-creating projects\", CFO.com]. https://www.cfo.com/capital-markets/2017/06/cfos-still-spurning-value-creating-projects/ †",
  "Harrison, G. W., Lau, M. I., & Williams, M. B. (2002). Estimating individual discount rates in Denmark: A field experiment. *American Economic Review, 92*(5), 1606–1617. https://doi.org/10.1257/000282802762024674",
  "Hausman, J. A. (1979). Individual discount rates and the purchase and utilization of energy-using durables. *Bell Journal of Economics, 10*(1), 33–54. https://doi.org/10.2307/3003318",
  "hdbinsights.sg. (2026). *4-room HDB rental yield*. https://hdbinsights.sg/4-room-hdb-rental-yield/ †",
  "Health Intervention and Technology Assessment Program. (n.d.). *Thai health technology assessment guidelines* [As summarised in PMC9969024]. https://pmc.ncbi.nlm.nih.gov/articles/PMC9969024/ †",
  "HM Treasury. (2026a). *Green Book supplementary guidance: Discounting*. https://www.gov.uk/government/publications/green-book-supplementary-guidance-discounting",
  "HM Treasury. (2026b). *Green Book discount rate review 2026* [Review by M. Freeman & B. Groom]. https://www.gov.uk/government/publications/green-book-discount-rate-review-2026 †",
  "Holston, K., Laubach, T., & Williams, J. C. (2023). *Measuring the natural rate of interest after COVID-19* (Staff Report No. 1063). Federal Reserve Bank of New York. https://www.newyorkfed.org/research/policy/rstar †",
  "Imai, T., Rutter, T. A., & Camerer, C. F. (2021). Meta-analysis of present-bias estimation using convex time budgets. *Economic Journal, 131*(636), 1788–1814. https://doi.org/10.1093/ej/ueaa115",
  "Jagannathan, R., Matsa, D. A., Meier, I., & Tarhan, V. (2016). Why do firms use high discount rates? *Journal of Financial Economics, 120*(3), 445–463. https://doi.org/10.1016/j.jfineco.2016.01.012",
  "JASPERS. (2021). *Economic appraisal vademecum 2021–2027: General principles and sector applications*. European Investment Bank. https://jaspers.eib.org/knowledge/publications/economic-appraisal-vademecum-2021-2027-general-principles-and-sector-applications",
  "Jordà, Ò., Knoll, K., Kuvshinov, D., Schularick, M., & Taylor, A. M. (2019). The rate of return on everything, 1870–2015. *Quarterly Journal of Economics, 134*(3), 1225–1298. https://doi.org/10.1093/qje/qjz012",
  "JTC Corporation. (2025). *MTI Committee of Supply 2025: Enhancements to the industrial land lease framework* [Press release]. https://www.jtc.gov.sg/about-jtc/news-and-stories/press-releases/mti-committee-of-supply-2025-enhancements-to-the-industrial-land-lease-framework",
  "Kwong, Goh, & Ti. (2025). Unpacking Singapore's leasehold relativity table. *International Real Estate Review, 28*(3), 379–406. https://ideas.repec.org/a/ire/issued/v28n032025p379-406.html † (author initials to confirm)",
  "Laibson, D. (1997). Golden eggs and hyperbolic discounting. *Quarterly Journal of Economics, 112*(2), 443–477.",
  "Laibson, D., Repetto, A., & Tobacman, J. (2007). *Estimating discount functions with consumption choices over the lifecycle* (NBER Working Paper No. 13314). National Bureau of Economic Research. https://www.nber.org/papers/w13314",
  "Lease decay and the prices of private residential properties in Singapore. (2022). *International Real Estate Review, 25*(3), 401–421. https://ideas.repec.org/a/ire/issued/v25n032022p401-421.html † (authors to confirm)",
  "Mapletree Industrial Trust. (2026). *Financial statements announcement* [Regulatory filing]. https://investor.mapletreeindustrialtrust.com/newsroom/20260428_201404_ME8U_B5K5LXJU7I2F5UP8.1.pdf †",
  "Matoušek, J., Havránek, T., & Iršová, Z. (2022). Individual discount rates: A meta-analysis of experimental evidence. *Experimental Economics, 25*(1), 318–358. https://doi.org/10.1007/s10683-021-09716-9",
  "Monetary Authority of Singapore. (n.d.-a). *MAS Standing Facility*. https://www.mas.gov.sg/monetary-policy/liquidity-facilities/mas-standing-facility",
  "Monetary Authority of Singapore. (n.d.-b). *Singapore's monetary policy framework: FAQs*. https://www.mas.gov.sg/monetary-policy/singapores-monetary-policy-framework/faqs/section-2",
  "Moore, M. A., Boardman, A. E., & Vining, A. R. (2013). More appropriate discounting: The rate of social time preference and the value of the social discount rate. *Journal of Benefit-Cost Analysis, 4*(1), 1–16. †",
  "Moore, M. A., Boardman, A. E., Vining, A. R., Weimer, D. L., & Greenberg, D. H. (2004). \"Just give me a number!\" Practical values for the social discount rate. *Journal of Policy Analysis and Management, 23*(4), 789–812.",
  "National Institute for Health and Care Excellence. (2022). *NICE health technology evaluations: The manual* (PMG36). https://www.nice.org.uk/process/pmg36/chapter/economic-evaluation-2",
  "New Zealand Treasury. (2024). *Discount rates*. https://www.treasury.govt.nz/information-and-services/public-sector-leadership/guidance/reporting-financial/discount-rates",
  "Norwegian Ministry of Finance. (2012). *Samfunnsøkonomiske analyser* [Cost-benefit analysis] (NOU 2012:16). https://www.regjeringen.no/en/documents/nou-2012-16/id700821/",
  "OECD. (2025). *Budgeting in Singapore in 2025*. OECD Publishing. https://www.oecd.org/content/dam/oecd/en/publications/reports/2025/01/budgeting-in-singapore-in-2025_c28f6afb/79ec8b00-en.pdf",
  "Office of Impact Analysis. (n.d.). *Cost-benefit analysis* [Guidance note]. Department of the Prime Minister and Cabinet, Australia. https://oia.pmc.gov.au/resources/guidance-assessing-impacts/cost-benefit-analysis",
  "Office of Management and Budget. (2003). *Circular A-4: Regulatory analysis*. https://obamawhitehouse.archives.gov/omb/circulars_a004_a-4/",
  "Office of Management and Budget. (2023). *Circular A-4: Regulatory analysis—Appendix* (rescinded 2025). https://bidenwhitehouse.archives.gov/wp-content/uploads/2023/11/CircularA-4Appendix.pdf",
  "Office of Management and Budget. (2025). *Rescission and reinstatement of Circular A-4* (Memorandum M-25-15). https://www.whitehouse.gov/wp-content/uploads/2025/03/M-25-15-Recission-and-Reinstatement-of-Circular-A-4.pdf",
  "Pharmaceutical Benefits Advisory Committee. (n.d.). *Guidelines for preparing a submission to the PBAC, Section 3A.1*. Australian Government Department of Health. https://pbac.pbs.gov.au/section-3a/3a-1-overview-and-rationale-of-economic-evaluation.html",
  "Plazzi, A., Torous, W., & Valkanov, R. (2010). Expected returns and expected growth in rents of commercial real estate. *Review of Financial Studies, 23*(9), 3469–3519.",
  "PropertyBro. (2026). *Commercial property investment yields in Singapore 2026: Sector guide*. https://propertybro.sg/commercial-property-investment-yields-in-singapore-2026-sector-guide/ †",
  "Rogoff, K. S., Rossi, B., & Schmelzing, P. (2024). Long-run trends in long-maturity real rates, 1311–2022. *American Economic Review*. https://www.nber.org/papers/w30475 † (volume/pages to confirm)",
  "S&P Global Market Intelligence. (2025). *Underearning spread widens for gas, electric utilities in ROE analysis*. https://www.spglobal.com/market-intelligence/en/news-insights/research/underearning-spread-widens-for-gas-electric-utilities-in-roe-analysis",
  "S&P Global Ratings. (n.d.). *SP PowerAssets Ltd.* [Credit research]. https://www.alacrastore.com/s-and-p-credit-research/SP-PowerAssets-Ltd-2764619 †",
  "Sanders, G. D., Neumann, P. J., Basu, A., Brock, D. W., Feeny, D., Krahn, M., Kuntz, K. M., Meltzer, D. O., Owens, D. K., Prosser, L. A., Salomon, J. A., Sculpher, M. J., Trikalinos, T. A., Russell, L. B., Siegel, J. E., & Ganiats, T. G. (2016). Recommendations for conduct, methodological practices, and reporting of cost-effectiveness analyses: Second Panel on Cost-Effectiveness in Health and Medicine. *JAMA, 316*(10), 1093–1103. https://doi.org/10.1001/jama.2016.12195 †",
  "Schleich, J., Gassmann, X., Faure, C., & Meissner, T. (2016). Making the implicit explicit: A look inside the implicit discount rate. *Energy Policy, 97*, 321–331. https://www.sciencedirect.com/science/article/pii/S0301421516304050",
  "Schmelzing, P. (2020). *Eight centuries of global real interest rates, R-G, and the 'suprasecular' decline, 1311–2018* (Staff Working Paper No. 845). Bank of England.",
  "Smets, F., & Wouters, R. (2007). Shocks and frictions in US business cycles: A Bayesian DSGE approach. *American Economic Review, 97*(3), 586–606. https://doi.org/10.1257/aer.97.3.586",
  "Stern, N. (2006). *Stern review on the economics of climate change*. HM Treasury.",
  "Federal Reserve Bank of St. Louis. (2026, May). *Comparing the FOMC's estimate of r-star with alternative estimates*. On the Economy. https://www.stlouisfed.org/on-the-economy/2026/may/comparing-fomc-estimate-r-star-alternative-estimates",
  "TIPSWatch. (2026, September 17). *10-year TIPS reopening gets real yield of 2.653%, highest in nearly 18 years*. https://tipswatch.com/2026/09/17/10-year-tips-reopening-gets-real-yield-of-2-653-highest-in-nearly-18-years/",
  "Trading Economics. (2026). *Singapore government bond 10Y*. https://tradingeconomics.com/singapore/government-bond-yield",
  "Train, K. (1985). Discount rates in consumers' energy-related decisions: A review of the literature. *Energy, 10*(12), 1243–1253.",
  "Treasury Board of Canada Secretariat. (2022). *Canada's cost-benefit analysis guide for regulatory proposals*. https://publications.gc.ca/site/eng/9.910204/publication.html",
  "van Binsbergen, J., Brandt, M., & Koijen, R. (2012). On the timing and pricing of dividends. *American Economic Review, 102*(4), 1596–1618. https://doi.org/10.1257/aer.102.4.1596",
  "Wang, M., Rieger, M. O., & Hens, T. (2016). How time preferences differ: Evidence from 53 countries. *Journal of Economic Psychology, 52*, 115–135. https://www.sciencedirect.com/science/article/abs/pii/S0167487015001439",
  "Weitzman, M. L. (2001). Gamma discounting. *American Economic Review, 91*(1), 260–271. https://doi.org/10.1257/aer.91.1.260",
  "Werkgroep discontovoet. (2025). *Rapport werkgroep discontovoet 2025* [Report of the discount rate working group]. Government of the Netherlands. https://www.rijksoverheid.nl/documenten/rapporten/2025/09/19/rapport-werkgroep-discontovoet-2025",
  "World Bank. (2016). *Discounting costs and benefits in economic analysis of World Bank projects* [Technical note]. https://documents.worldbank.org/en/publication/documents-reports/documentdetail/099610503022315638 †",
  "World Health Organization. (2003). *Making choices in health: WHO guide to cost-effectiveness analysis* (T. Tan-Torres Edejer et al., Eds.).",
  "Zhuang, J., Liang, Z., Lin, T., & De Guzman, F. (2007). *Theory and practice in the choice of social discount rate for cost-benefit analysis: A survey* (ERD Working Paper No. 94). Asian Development Bank. https://www.adb.org/sites/default/files/publication/28360/wp094.pdf",
  "Zorginstituut Nederland. (2024). *Richtlijn voor het uitvoeren van economische evaluaties in de gezondheidszorg* [Guideline for economic evaluations in healthcare]. https://www.zorginstituutnederland.nl/publicaties/publicatie/2024/01/16/richtlijn-voor-het-uitvoeren-van-economische-evaluaties-in-de-gezondheidszorg",
];
